In [1]:
import pandas as pd
import numpy as np

In [5]:
data = {
    'Sex': ['male','female', 'male'],
    'Alive': [True, np.nan, False],
    'Age': [18, 22, np.nan]
}
df = pd.DataFrame(data)
print(df)

df.fillna(-1)
print(df.fillna(-1))

      Sex  Alive   Age
0    male   True  18.0
1  female    NaN  22.0
2    male  False   NaN
      Sex  Alive   Age
0    male   True  18.0
1  female     -1  22.0
2    male  False  -1.0

In [21]:
t =

In [23]:
df[pd.isna(df).values]

      Sex  Alive   Age
1  female    NaN  22.0
2    male  False   NaN

In [25]:
f = df[pd.isna(df).values]
print(f)

      Sex  Alive   Age
1  female    NaN  22.0
2    male  False   NaN

In [26]:
df

      Sex  Alive   Age
0    male   True  18.0
1  female    NaN  22.0
2    male  False   NaN

In [47]:
for i in df[['Age']].index:
    if pd.notna(df[['Age']].iloc[i].item()):
        df.at[i ,'Age'] = 1

In [48]:
df

      Sex  Alive  Age
0    male   True  1.0
1  female    NaN  1.0
2    male  False  NaN